default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: react_recipme_development

test:
  <<: *default
  database: react_recipme_test

production:
  <<: *default
  database: react_recipme_production
  username: react_recipme
  password: <%= ENV['REACT_RECIPME_DATABASE_PASSWORD'] %>
